# Site Settings
title: Classy Ultimate
email: mskeving@gmail.com
description: >
  Bay Area Blappers
baseurl: ""
url: "http://localhost:4000"
twitter_username: classyultimate
facebook_username: classyultimate
cdn_url: "https://s3-us-west-1.amazonaws.com/classyultimate/"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM